### ISSUE TITLE
[TB-8] Select DB

### ISSUE THREAD

**Issue by vpakhuchyi** [GolangUA/telegram-butler#10]
Describe the comparison of available DB (price, characteristics etc). 
Data to be stored:
- info about bans
- info about pardon (recovery)
- validation rules
- onboarding content

**Comment by mymmrac** [comment]
Possible routes:
- https://www.mongodb.com - 512 MB, free
- https://www.cockroachlabs.com - 10 GB, free
- https://neon.tech - 512 MB, free
- https://cloud.google.com/storage - 5 GB, free
- https://cloud.google.com/storage - 1 GB, free

**Comment by mymmrac** [comment]
Since we don't need a lot of storage and most likely will go with NoSQL DB most logical step will be to go with Firestore

**Comment by mymmrac** [comment]
Wiki: https://github.com/GolangUA/telegram-butler/wiki/Database
